# -*- coding: utf-8 -*-
"""Reseller credit management API params. Mirrors vendor sgc_reseller_credit_management_api_params."""

API_RESELLER_CREDIT_MANAGEMENT_API_NAME = "credit"
API_RESELLER_CREDIT_MANAGEMENT_CREDIT = "credits"
API_RESELLER_CREDIT_MANAGEMENT_PRODUCT = "product"
API_RESELLER_CREDIT_MANAGEMENT_TRANSACTION_TYPE = "transactiontype"
API_RESELLER_CREDIT_MANAGEMENT_COMMENT = "comment"
API_RESELLER_CREDIT_MANAGEMENT_USER_LOGIN_NAME = "userloginname"
API_RESELLER_CREDIT_MANAGEMENT_FROM_DATE = "fromdate"
API_RESELLER_CREDIT_MANAGEMENT_TO_DATE = "todate"
API_RESELLER_CREDIT_MANAGEMENT_EXPIRYDATE = "expiryDate"
